### ISSUE TITLE
요구사항 명세서 작성

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/iothome#1]
구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다.
@pyj9293 여러가지모드, 날씨
@MyungwoonKim 음악기능, 스케쥴
@sayujin 온습도 센서, 아두이노 통신 - 통신방법은 결합이 아닌 무선으로 가능한 방법입니다.
@LeeJinYeong 스마트폰 알림, 알람
@hJayLee 음성인식, 조크기능

**Comment by pyj9293** [comment]
코멘트 예) 

> 구글드라이버 1.요구분석 > 요구사항 명세서 작성이 필요합니다 - 음악기능, 스케쥴
완료했습니다 검토 바랍니다

**Comment by MyungwoonKim** [comment]
>test
test

**Comment by MyungwoonKim** [comment]
>test

test

**Comment by pyj9293** [comment]
코멘트 예)

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다 - 여러가지모드, 날씨

완료했습니다 검토바랍니다.

**Comment by LeeJinYeong** [comment]
확인했습니다

**Comment by LeeJinYeong** [comment]
부품 조사 마이크 업데이트 했습니다.

**Comment by pyj9293** [comment]
@MyungwoonKim @sayujin @LeeJinYeong @tti0506 

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 여러 가지 모드

여러 가지 모드 기능에서 방해 금지 모드 말고 다른 모드에 대한 아이디어가 있으면 얘기 좀 해주시기 바랍니다.

**Comment by tti0506** [comment]
> 여러 가지 모드 기능에서 방해 금지 모드 말고 다른 모드에 대한 아이디어가 있으면 얘기 좀 해주시기 바랍니다.

@pyj9293

**Comment by pyj9293** [comment]
@MyungwoonKim @sayujin @LeeJinYeong @tti0506

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 여러가지모드, 날씨

요구 사항 명세서 완료했습니다. 검토 바랍니다.

**Comment by jyleeeeeeeeee** [comment]
@pyj9293 @MyungwoonKim @sayujin @tti0506

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 스마트폰 알림, 알람 

완료했습니다 검토바랍니다

**Comment by hJayLee** [comment]
@pyj9293 @MyungwoonKim @sayujin @LeeJinYeong 

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 음성인식

1차적으로 완료했습니다. 검토 바랍니다.

그리고 시동어는 음성인식 기능을 실행하기 위해 정의된 단어이고, 각각 해당 기능을 수행하기 위한 단어들은 시동어라고 표현하기 보단 명령어 등의 표현으로 바꾸는 것이 좋다고 생각됩니다. ex) (시동)아이오톰, (명령)전화걸어줘

**Comment by sayujin** [comment]
@pyj9293 @LeeJinYeong @MyungwoonKim   @hJayLee 

> 구글 드라이브 1.요구분석 >요구사항 명세서 작성이 필요합니다. -온습도 센서

아두이노 통신 부분은 아직 검토 중 입니다. 온습도 관련 기능 완료했습니다.

**Comment by MyungwoonKim** [comment]
@pyj9293 @LeeJinYeong @hJayLee @sayujin 

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 음악, 스케줄

작성 완료했습니다..

**Comment by MyungwoonKim** [comment]
@pyj9293 @LeeJinYeong @hJayLee @sayujin

각 기능별 비기능적 요구 추가 부탁드립니다.

**Comment by pyj9293** [comment]
@MyungwoonKim 

> 각 기능별 비기능적 요구 추가 부탁드립니다.

알겠습니다. 추가하겠습니다.

**Comment by pyj9293** [comment]
@LeeJinYeong @sayujin  @hJayLee @MyungwoonKim 
날씨 정보를 받기위한 위치정보를 어떻게 받을지에 대한 이슈입니다.
gps
- gps 모듈을 이용하면 되긴하는데 그 모듈에 있는 **안테나가 실외에 있어야 위치정보을 얻을 수 있음**
- 위치정보 시간은 **2분 이상 걸림**

wifi 위치정보
- ap 수신기 3개를 설치해야하고 계산 해야하는 것이 너무 많음 
- 저희 팀의 현실상 구현 **불가능하다고 판단됨**

**직접 설정**
- [x] 1. 폰으로 위치를 설정
  - (명령어)날씨 좀 알려줘 (응답)현재 위치가 저장되어 있지 않습니다. 폰을 이용하여 위치를 추가하여 
    주세요
- [ ]  2. 음성으로 위치를 입력 
  - (명령어)날씨 좀 알려줘 (응답)현재 위치가 저장되어 있지 않습니다. 위치를 추가 하시겠습니까? 
    (명령어) 해줘 (응답) 도시를 말해 주세요 (명령어) 삼척시 (응답) 설정 되었습니다
  - (명령어) 날씨 위치 변경해줘 ~~~~~~~~
  
  **1번으로 할지 2번으로 할지 얘기 해 주세요.**

**Comment by hJayLee** [comment]
> 1. 폰으로 위치를 설정
> 
> (명령어)날씨 좀 알려줘 (응답)현재 위치가 저장되어 있지 않습니다. 폰을 이용하여 위치를 추가하여 주세요

저희가 개발할 웹 자체에서 지역을 설정할 수 있게 하고, 라즈베리파이에서 해당 정보를 통해 날씨 설정을 하는 것이 좋아보입니다.

**Comment by sayujin** [comment]
> 1. 폰으로 위치를 설정
> 
> (명령어)날씨 좀 알려줘 (응답)현재 위치가 저장되어 있지 않습니다. 폰을 이용하여 위치를 추가하여 주세요

음성으로 위치를 받는 것 보다는 폰으로 받는 것이 더 좋은 것 같습니다.   음성으로 입력을 할 기능이 많아 질 경우 너무 음성 인식 기능에 치중하다 보니 복잡해질 것 같습니다. 변동이 별로 되지 않을 정보들은 웹이든 폰이든 설정을 해놓게 하는 것이 더 효율적 같아 보입니다.

**Comment by jyleeeeeeeeee** [comment]
@pyj9293 

> 1. 폰으로 위치를 설정
> 
> (명령어)날씨 좀 알려줘 (응답)현재 위치가 저장되어 있지 않습니다. 폰을 이용하여 위치를 추가하여 주세요

폰으로 하는 것이 설정하기도 쉽고 개발하기에 용이하다고 생각합니다.

**Comment by pyj9293** [comment]
@LeeJinYeong @hJayLee @sayujin 

알겠습니다. 확인했습니다.

**Comment by MyungwoonKim** [comment]
@pyj9293

> 1. 폰으로 위치를 설정
> 
> (명령어)날씨 좀 알려줘 (응답)현재 위치가 저장되어 있지 않습니다. 폰을 이용하여 위치를 추가하여 주세요

보통의 경우는 날씨 정보는 주기적으로 미리 받아놓고 디스플레이 하는것이 대부분입니다. 그 이유는 날씨의 변동이 그리 크지 않기 때문입니다.

**Comment by MyungwoonKim** [comment]
@pyj9293 @LeeJinYeong @hJayLee @sayujin 

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 음악, 스케줄

기능 세분화 및 추가 완료했습니다.

**Comment by pyj9293** [comment]
@MyungwoonKim 

> 보통의 경우는 날씨 정보는 주기적으로 미리 받아놓고 디스플레이 하는것이 대부분입니다. 그 이유는 날씨의 변동이 그리 크지 않기 때문입니다.

예 그건 알고 있지만, 디스플레이를 할 때 어떻게 위치를 보여주냐에 관한 이슈였습니다

**Comment by pyj9293** [comment]
@MyungwoonKim 

> 기능세분화 및 추가 완료했습니다.

스케쥴 기능정의에서 구글 캘린더에 대한 내용을 알리는 것과
**목소리로 스케줄 추가, 삭제**하는 것은 어떤가요?

**Comment by MyungwoonKim** [comment]
@pyj9293 
당연히 날씨 정보를 미리 불러오기 위해서는 위치 정보도 미리 불러와야 합니다. 이슈에 근거가되는 위치 정보가 제가 말한 위치 정보와 뭐가 다른지 모르겠네요.

**Comment by hJayLee** [comment]
@pyj9293 @LeeJinYeong @sayujin @MyungwoonKim

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다. - 음성인식

비기능적 요구 작성 완료하였습니다. 농담기능은 기본적으로 듣고 말하는 것 외에 필요한 부분이 없어 보류하였습니다.

그리고 우리가 개발할 부분은 앱이 아닌 웹이기 때문에 시스템 정의에 '안드로이드'로 명시되어 있는 부분을 '웹'으로 수정하는 것이 옳다고 생각합니다. 이 부분에서 어떻게 생각하시는지요?

**Comment by hJayLee** [comment]
음성인식	듣기	VR001	기본적으로 구글 API의 받아쓰기를 토대로 직접 입력한 단어DB를 통해 비교 및 인식한다. 그리고 구글 음성인식 API에 기본적으로 탑재되어 있는 기능(날씨 알려줘)들 또한 활용하여 두가지 방식으로 인식 알고리즘을 구상해야한다. 인식된 단어와 함수에 입력되어 있는 단어를 비교하여 올바를 경우 기능을 수행한다			라즈베리파이	
음성인식	말하기	VR002	올바르게 인식되어 기능이 동작할 때 해당에 기능을 수행하겠다는 알림과 함께, 적절한 단어가 인식되지 않으면' VR002 다시묻기' 를 수행한다.			라즈베리파이	
음성인식	다시묻기	VR003	음성으로 받아쓰기된 단어가 단어DB에 존재하지 않을 때, 알림과 함께 다시 한번 'VR001 듣기'를 수행한다.			라즈베리파이	
음성인식	확인하기	VR004	전화 및 문자 등 수행 전에 한번 더 확인이 필요한 작업들은 입력된 내용이 정확한지 사용자에게 되묻고, 올바르다는 답변을 얻었을 경우 최종적으로 기능을 수행한다.			라즈베리파이	
음성인식	농담하기	VR005	보류			라즈베리파이

**Comment by pyj9293** [comment]
@LeeJinYeong @hJayLee @sayujin @MyungwoonKim 

> 구글드라이브 1.요구분석 > 요구사항 명세서 작성이 필요합니다 - 여러가지모드, 날씨

요구사항 명세서 기능, 비기능 정의 완료했습니다.

**Comment by pyj9293** [comment]
방해금지 모드에 대한 이슈가 있습니다
1. 방해금지모드에 대한 근본적인 필요성에 대한 문제
2. 원래 처음 요구 했을 경우 잘 때나 알림을 듣고 싶지 않을 경우에 문제를 해결하기 위해 방해금지 모드가 생겼으므로
   핸드폰에서 쓰는 무음 모드가 적합하다고 생각됨
3. 원래 요구했던 대로 방해금지모드를 사용할 경우 
    - 핸드폰과 라즈베리파이, 라즈베리파이와 DB에 대한 통신 문제
    - 웹에서 설정될 때마다 라즈베리파이에서도 실시간으로 설정되어야하는 부분
   의 복잡한 문제가 발생됨

그러므로 방해금지모드에 대한 필요성과 기능을 구현할 경우 너무 복잡하게 되는 문제가 있어 무음 모드로 바꿔야 한다고 생각 됩니다

- 비기능적 요구
![2017-02-26 11 54 56](https://cloud.githubusercontent.com/assets/16908979/23336695/734064e8-fc1a-11e6-8fb7-e435c4c30ab5.png)

- 기능적 요구
![2017-02-26 11 54 39](https://cloud.githubusercontent.com/assets/16908979/23336696/7382d328-fc1a-11e6-8aaf-96db49b71fb1.png)

**Comment by MyungwoonKim** [comment]
@pyj9293

확인 했습니다. 관련된 문서 전체 수정 바랍니다.

**Comment by pyj9293** [comment]
@MyungwoonKim 알겠습니다 
요구사항 분석 close시키겠습니다
