### ISSUE TITLE
음성인식 질의를 통한 TTS응답 출력하기

### ISSUE THREAD

**Issue by hJayLee** [pyj9293/iothome#11]
음성인식 API가 정상적으로 구동됨에 따라 음성인식 결과를 문자열 값으로 받아올 계획입니다.
이 값을 통해 특정 질의에 따라 해당하는 응답을 출력할 수 있도록 할 예정이며 텍스트 출력이 완료되면 거기에 TTS 음성 출력까지 더해보도록 하겠습니다.

**Comment by hJayLee** [comment]
> http://translate.google.com/translate_tts?ie=UTF-8&total=1&idx=0&textlen=32&client=tw-ob&q=안녕하세요%20제%20이름은%20아이오톰%20입니다&tl=ko-gb

위 구글 TTS를 활용하면 쉽게 구현할 수도 있을 것 같습니다.

**Comment by pyj9293** [comment]
1. 네이버 음성합성 api를 이용

 >  https://developers.naver.com/docs/labs/tts

2. 네이버에 나오는 기본예제는 python 3.x 버젼에서 하는 방법으로 라이브러리를 3.x를 받아야 합니다

![image](https://cloud.githubusercontent.com/assets/16908979/21741482/80719b40-d51a-11e6-800d-681877b60281.png)

3. 파이썬을 실행 할 경우 .mp3파일로 저장됩니다.

- 텍스트 입력
![image](https://cloud.githubusercontent.com/assets/16908979/21741729/9b930ad2-d522-11e6-8295-77695c33d64e.png)

- 저장된 mp3 실행
드라이브 - 99.기타 - 음악합성.mp3

**Comment by pyj9293** [comment]
검토 바랍니다

**Comment by MyungwoonKim** [comment]
검토 했습니다. 
목소리 종류는 뭐로 할 생각이신가요?

**Comment by pyj9293** [comment]
> 목소리 종류는 뭐로 할 생각이신가요?

방법이 두가지 있습니다
1.  목소리 설정을 따로 두어서 사용자가 원하는 목소리를 설정할 수 있게 하는 방법
2.  회의를 통해 목소리를 결정하는 방법

하지만 지금은 목소리를 무엇을 할 것인가는 중요하지 않은것 같습니다

**Comment by hJayLee** [comment]
개발 중간 보고 드립니다.
결론적으로 현재 음성인식 -> 텍스트 생성 -> 음성합성 -> mp3생성 및 출력까지 가능합니다.

세부적인 설명은 다음과 같습니다.
> 1. transcribe_streaming.py(구글 음성인식)를 실행하면 음성인식 기능이 활성화됩니다.
> 2. 입력된 음성에 대한 값을 txt파일로 저장하도록 추가적으로 코딩하였습니다.
> 3. 생성된 txt파일은 nvoice.py(네이버음성합성+mp3재생)에서 읽은 후 음성합성을 거쳐 mp3파일로 생성됩니다.
> 4. 생성된 mp3 파일은 바로 재생됩니다.

발견되는 문제점은 다음과 같습니다.
> 1. 파이썬2버전과 3버전 간의 호환성 문제
> 2. py들을 어떻게 하나로 묶을 것인가

현재 음성인식으로 입력된 값을 활용할 수 있는 정도이며, 앞으로는 질의에 대해 알맞은 응답을 선택할 수 있는 코드를 삽입해보려고 합니다. 이상이며 의견 부탁드립니다.
