### ISSUE TITLE
방해 금지 모드(스피커 제어) 테스트

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/iothome#12]
> @pyj9293 방해금지 모드의 상태에 따라 라즈베리파이 스피커를 제어하는 방법 테스트

**Comment by pyj9293** [comment]
파이썬으로 라즈베리파이 스피커 볼륨 제거하기를 완료했습니다
참고 : http://askubuntu.com/questions/689521/control-volume-using-python-script

파이썬 실행
![2017-01-09 2 35 27](https://cloud.githubusercontent.com/assets/16908979/21757918/e39cb560-d678-11e6-8c28-f0aa1acbd47a.png)

실행 후 볼륨 상태
![2017-01-09 2 34 37](https://cloud.githubusercontent.com/assets/16908979/21757904/c6ce88fa-d678-11e6-8e30-ebb76fe557dd.png)

검토바랍니다

**Comment by MyungwoonKim** [comment]
검토 완료했습니다.
