### ISSUE TITLE
구글STT와 네이버TTS를 대체하기 위한 Jasper 오픈 소스 플랫폼

### ISSUE THREAD

**Issue by hJayLee** [pyj9293/iothome#15]
먼저 Jasper란 STT와 TTS를 결합하고 있는 오픈 소스 플랫폼입니다.
가장 큰 특징으로 100% 오픈 소스라는 점과 Always-Listening(항상 음성인식 대기상태에 놓여있는 것), 그리고 음성인식을 통한 제어 방법을 기본적으로 제공하고 있다는 것입니다.
자세한 사항은 아래 주소를 참고 해주시기 바랍니다.

> https://jasperproject.github.io/

**Comment by pyj9293** [comment]
@hJayLee 아주 좋은 모듈이네요 
근데 이 모듈을 따로 설계 할 필요가 있을까요??

**Comment by hJayLee** [comment]
Jasper에 대해서 조사 도중에 annyang이라는 플랫폼을 찾았는데 Jasper보다 훨씬 간단합니다. 기본적으로 자바스크립트로 구현되어 있는데 이 부분이 큰 영향을 미치는 지 의견이 필요합니다.
annyang에 대해서는 아래 설명을 통해 확인해주시기 바랍니다.

> https://www.talater.com/annyang/

**Comment by hJayLee** [comment]
오래 걸렸습니다.. Jasper 셋팅 결과. 현재 아주 잘 작동합니다. 

> 먼저 Jaspser 설치는 전혀 문제가 없었지만 Jasper 특성 상 STT와 TTS 엔진을 선택할 수 있게 해둔 부분에서 Default 엔진 설치 과정에 문제가 있었습니다.

> STT는 Default 엔진인 PocketSphinx STT 엔진설치를 생략하고 구글 STT로 설정하여 해결하였고, 정상적으로 구동이 되었습니다.

> 여기서 STT 인식 후에 TTS를 통한 응답이 전혀 이루어지지 않아 Debug 모드를 통해 mp3를 재생하는 aplay에 문제가 있다는 것을 발견하였습니다. 라즈비안을 위한 사운드카드 수동 선택 명령어가 문제였고, 해당 부분을 삭제하여 해결하였습니다.

> 결론적으로 구글 STT & eSpeak TTS 엔진을 통해 Jasper 운용이 가능했고 기본적으로 탑재되어 있는 시간 묻기 기능 정도를 수행할 수 있었습니다.

* 참고로 구글 STT는 이전에 사용하던 구글 Cloud Speach API 가 아닌
https://groups.google.com/a/chromium.org/forum/#!forum/chromium-dev 를 가입해야 구글 API 콘솔에서 검색이 가능한 구글 STT API 을 사용합니다. 그렇기 때문에 인식률이 이전보다 낮다는 점과 함께 Jasper에서는 Cloud STT를 사용할 수 없다고 합니다.

이제 Jasper에 기본 탑재 되어있는 기능(Modules)를 분석해서 추가적인 기능을 부가하기 위한 부분과 이에 따른 클래스다이어그램 작성을 할 예정입니다.

**Comment by hJayLee** [comment]
기능 모듈에 대한 코드 좀 살펴보았습니다. 일단 가장 간단하고 대표적인 '시간 묻기 모듈' 에 대한 코드입니다. (/home/pi/jasper/client/modules/Time.py)

```
import datetime
import re
from client.app_utils import getTimezone
from semantic.dates import DateService

WORDS = ["TIME"]	
# 각 모듈에 대한 구분을 위해 명시하는 코드입니다.

def handle(text, mic, profile):
           tz = getTimezone(profile)
          now = datetime.datetime.now(tz=tz)	
          service = DateService()
          response = service.convertTime(now)
          mic.say("현재 시각은 %s 입니다." % response)
          # Profile에 등록된 지역에 따른 시간정보를 불러와 STT에 대한 TTS 음성출력을 위한 코드입니다.

def isValid(text):
          return bool(re.search(r'\btime\b', text, re.IGNORECASE))
          # 입력된 음성과 비교하기 위한 코드입니다. 한글을 사용하기 위해서는 
          # return bool(re.search(ur'시간', phrase, re.UNICODE))
          # 과 같은 방식으로 수정해야합니다.
```

Jasper가 실행되면 client/brain.py에서 modules 폴더를 탐색해 각 모듈들을 불러오는 과정을 거칩니다. 그렇기 때문에 위와 같은 형식으로 코딩을 한 후 pyc 파일로 컴파일해두면 자동으로 모듈을 인식합니다. 해당 부분은 아래와 같이 테스트를 거쳤습니다.

![1](https://cloud.githubusercontent.com/assets/22610690/22358806/97aae800-e485-11e6-9412-2f5eb12ab4da.PNG)
test.py 를 생성해서 컴파일하는 과정입니다.

![2](https://cloud.githubusercontent.com/assets/22610690/22358809/9993907c-e485-11e6-9851-00f486d917e1.PNG)
modules를 폴더를 탐색해 맨 아래 test 모듈을 불러온 것을 확인할 수 있습니다.

**Comment by MyungwoonKim** [comment]
@hJayLee  확인했습니다. 
수고하셨습니다.
