### ISSUE TITLE
SoundCloud API Key 발급 문제 시 대체 방안

### ISSUE THREAD

**Issue by MyungwoonKim** [pyj9293/iothome#17]
사운드 클라우드 API키가 발급 취소 되었습니다.
Key의 발급 기간은 평균 2~4주 걸립니다.
또한 발급 기준도 까다로워 발급 거부 될 수도 있습이다.
발급 거부 시 youtube를 이용할까 합니다. 다른 방안 알고 있으신 분은 코맨트 달아주세요.

**Comment by pyj9293** [comment]
@MyungwoonKim 
1. 갑자기 발급 취소 된 이유가 뭔가요??

2. 유튜브를 이용했을시에 사운드 클라우드처럼 목소리로 자유자재로 음악을 실행 실킬수 있나요?

**Comment by MyungwoonKim** [comment]
@pyj9293

1. 모르겠습니다. 추정컨데 초기 일정한 트래픽이 발생히지 않아 그런것 같습니다.
2. 검색하는 API는 존재하나 검색 후 바로 재생히는 기능은 개별적으로 구현이 필요해 보이며 기본적으로 영싱이 츨력되는 부분을 따로 수정해야 할 것 같습니다.
