### ISSUE TITLE
Youtube API를 이용해 SoundCloud 대체

### ISSUE THREAD

**Issue by MyungwoonKim** [pyj9293/iothome#18]
@MyungwoonKim

SoundCloud를 대체하기 위해 다음 3가지 요소의 테스트가 필요합니다.
1. API키 발급
2. 질의어를 통한 검색기능
3. 영상 재생 시 음성만 출력 할 수 있는지, 별도의 컨트롤러를 사용할 수 있는지 테스트

**Comment by MyungwoonKim** [comment]
>1. API키 발급
>2. 질의어를 통한 검색기능

테스트 진행 과정은 다음과 같습니다.

![image](https://cloud.githubusercontent.com/assets/22610670/22073111/c60b78d0-dde7-11e6-95f9-a75521d7c991.png)
OAuth 2.0 클라이언트 ID 발급 한 뒤 js파일에 적용
키워드를 입력하고 난 뒤 검색 후 JSON 형태로 출력

- 실행화면
![image](https://cloud.githubusercontent.com/assets/22610670/22073330/6cf8fad2-dde8-11e6-9f06-995a2b80642c.png)

- JSON 확인
![image](https://cloud.githubusercontent.com/assets/22610670/22073459/c06e0ea0-dde8-11e6-9ffd-c44ea6f203c1.png)

- Youtube 검색 결과와 비교
![image](https://cloud.githubusercontent.com/assets/22610670/22073531/e8a5e73a-dde8-11e6-9d99-d9d95a4230b8.png)

- 비디오 ID 비교
![image](https://cloud.githubusercontent.com/assets/22610670/22073643/30619d12-dde9-11e6-95bf-84ee5ee77b74.png)

API 인증 및 검색 테스트 결과 IFrame src에 해당 비디오 ID를 넣는 방식으로 SoundCloud의 검색 기능을 대체할 수 있습니다.

검토 부탁드립니다.

**Comment by pyj9293** [comment]
검토 완료했습니다

> 3. 영상재생 시 음성만 출력 할 수 있는지, 별도의 컨트롤러를 사용할 수 있는지 테스트

3번이 되는 것이 중요하다 생각됩니다

**Comment by MyungwoonKim** [comment]
>3. 영상재생 시 음성만 출력 할 수 있는지, 별도의 컨트롤러를 사용할 수 있는지 테스트

iframe 자체에서 영상 출력을 막는 API는 존재하지 않습니다. 또한 별도에 video 태그를 사용할 수 없기에 별도에 컨트롤러도 사용할 수 없습니다.

그래서 해결 방안은 다음과 같습니다.

1, youtube api중 별도에 영상을 제어하는 콘솔 api가 존재함으로 이 api를 이용해 자바스크립트로 별도에 컨트롤러를 생성
2. . css3를 이용해 iframe을 visibility: hidden속성을 부여

위 결과를 통해 마치 컨트롤러를 통해 음악을 제어하는 것 처럼 사용자에게 UX를 유도합니다. 

검토 부탁드립니다.

**Comment by pyj9293** [comment]
> iframe 자체에서 영상 출력을 막는 API는 존재하지 않습니다. 또한 별도에 video 태그를 사용할 수 없기에 별도에 컨트롤러도 사용할 수 없습니다.
> 
> 그래서 해결 방안은 다음과 같습니다.
> 
> 1, youtube api중 별도에 영상을 제어하는 콘솔 api가 존재함으로 이 api를 이용해 자바스크립트로 별도에 컨트롤러를 생성
> 2. . css3를 이용해 iframe을 visibility: hidden속성을 부여
> 
> 위 결과를 통해 마치 컨트롤러를 통해 음악을 제어하는 것 처럼 사용자에게 UX를 유도합니다.
> 
> 검토 부탁드립니다.

@MyungwoonKim  검토했습니다 이대로 진행부탁드립니다.
