### ISSUE TITLE
DB 자료사전 작성

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/iothome#19]
@LeeJinYeong @sayujin @MyungwoonKim @pyj9293
드라이브/설계/웹/DB DATA/ DB 자료사전

![image](https://cloud.githubusercontent.com/assets/16908979/22532916/00ddc61a-e92e-11e6-82fc-3ac207d11b58.png)

이와 같이 작성

**Comment by MyungwoonKim** [comment]
@pyj9293 
캘린더 및 유투브 스트리밍 기반 구글 계정 DB데이터 작성 완료했습니다.

**Comment by pyj9293** [comment]
날씨 및 방해금지모드에 대한 DB자료사전 작성 완료했습니다

**Comment by sayujin** [comment]
무드등, 온습도 , 미세먼지에 대한 DB 자료사전 작성 완료했습니다.

**Comment by MyungwoonKim** [comment]
@sayujin 
온습도 필드 중 온도, 습도 필드 명이 날씨 필드의 온도 습도 필드와 동일합니다.
온습도의 온도, 습도의 경우 현재 또는 현재 공간 이라는 의미를 포함한 필드명으로 변경이 필요해 보입니다.

**Comment by sayujin** [comment]
@MyungwoonKim
그 부분은 이야기 해보고 결정하겠습니다
