### ISSUE TITLE
부품 조사

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/iothome#2]
@LeeJinYeong 구글 드라이버 99.기타 > 부품 조사가 필요합니다.

**Comment by jyleeeeeeeeee** [comment]
마이크, 온습도 센서 부분 업데이트 완료했습니다.

**Comment by pyj9293** [comment]
> 마이크, 온습도 센서 부분 업데이트 완료했습니다.

확인 했습니다 완료하겠습니다
