### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by MyungwoonKim** [pyj9293/iothome#27]
@pyj9293 
자료는 드라이브의 DB데이터를 참조하시고,
ERD 형식은 크로우즈 핏 기반으로 작성바랍니다.

**Comment by pyj9293** [comment]
![2017-02-13 9 30 35](https://cloud.githubusercontent.com/assets/16908979/22883463/b2be7dee-f233-11e6-8fdb-7d63ef4fd558.png)

작성 완료했습니다.

유튜브와 캘린더 부분은 나타내기만 한 것으로 신경쓰실 필요 없고
환경, 알람, 방해금지만 신경 쓰면 됩니다
생각보다 관계가 너무없어서 이렇게 하면 되는지 잘 모르겠지만,
보고 검토 부탁드립니다.
