### ISSUE TITLE
웹기반 모듈 컨트롤러 개발환경 및 메인 프론트 엔드 메인화면 초안 작업

### ISSUE THREAD

**Issue by MyungwoonKim** [pyj9293/iothome#28]
@MyungwoonKim

HTML5, CSS3를 이용한 메인 화면 초기 프론트 엔드 작업
화면 설계 참조.

**Comment by MyungwoonKim** [comment]
메인화면 프론트엔드 초안 작업 완료했습니다.

* 해드 부분은 jsp:include를 사용하여 모듈화 시켰고 푸터의 경우 화면설계에 존재하지 않아 작성하지 않았습니다. 
![image](https://cloud.githubusercontent.com/assets/22610670/22862491/feba6882-f172-11e6-849b-802e148fee8e.png)


* 각각 기능의 스타일 시트와 자바스크립트를 별도의 파일로 구성하였습니다.
![image](https://cloud.githubusercontent.com/assets/22610670/22862492/0de28894-f173-11e6-8aff-df866fd628e0.png)
normalize.css 파일은 웹 표준을 맞출 수 있게 css를 이용한 표준화한 파일이니 모든 주된 jsp파일에 적용하시면 됩니다.


* 부트스트랩을 이용한 CDM은 다음과 같습니다. 이 또한 주된 jsp파일에 적용하시면 됩니다.
![image](https://cloud.githubusercontent.com/assets/22610670/22862499/437ac85e-f173-11e6-9058-4983fb0ba72e.png)


뼈대만 잡아 놓았기 때문에 추후 결정된 디자인 컨셉과 기능에 따라 변경될 수 있습니다.
자세한 코드는 Github code란에 iothomeController프로젝트에서 확인하실 수 있습니다.

검토 부탁드립니다.

**Comment by pyj9293** [comment]
확인 했습니다.

질문
1. 세팅 리스트를 캘린더 밑에 메인에다 보여 줄 것이므로 추가 부탁 드립니다 
2. 세팅 리스트를 보면 두가지 방식이 있는데  
   - [ ]  (1) 리스트 형식
   - [ ]  (2) 카드 형식
   - [ ]  (3) 반응형으로 웹에서 볼때는 카드형식, 스마트폰에서 볼때는 리스트형식

  체크 부탁 드립니다. (드라이브/설계/화면설계서/웹/설정리스트 에 나와있으니까 참고 바람)

**Comment by MyungwoonKim** [comment]
메인화면에 세팅 리스트를 추가했습니다.

세팅 리스트방식은 질문 2-3에 맞게 카드와 리스트 형식을 동시에 표현하였습니다. 
프레임은 다음과 같습니다.
![image](https://cloud.githubusercontent.com/assets/22610670/22931104/c42a9c74-f306-11e6-8528-ce93d5fb35a4.png)

또한 상단에 네비게이션바에서 Setting을 누르면 셋팅 리스트로 이동하게 수정하였습니다.

자세한 코드는 Github code란에 initialDesign브랜치에 iothomeController프로젝트에서 확인하실 수 있습니다.

검토 부탁드립니다.
