### ISSUE TITLE
라즈베리파이와 안드로이드 블루투스 통신

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/iothome#32]
스마트폰과 라즈베리파이의 블루통신을 통해서 스마트폰에서 쓰는 어플 및 전화 문자의 푸시알림을 동기화하여
라즈베리파이에서 푸시알림을 하게 한다

**Comment by pyj9293** [comment]
![2017-03-12 4 01 52](https://cloud.githubusercontent.com/assets/16908979/23829743/44746654-073d-11e7-9261-af346051b755.png)


1. 안드로이드 notification()을 이용하여 문자, 전화에 대한 정보를 앱을 만들어 가져온다.
2. 안드로이드 bluetoothAdapter를 이용하여 라즈베리파이에 전송한다
3. 라즈베리파이에서 실시간으로 전송을 받으면 스피커로 알림에 대한 정보를 출력한다

 [참고 URL](http://webnautes.tistory.com/995)

**Comment by MyungwoonKim** [comment]
@pyj9293 
검토 완료했습니다. 수고하셨습니다.
