### ISSUE TITLE
라즈베리파이 Git 환경 구축 및 사용 방법

### ISSUE THREAD

**Issue by MyungwoonKim** [pyj9293/iothome#41]
@pyj9293 @sayujin @hJayLee 

현재 저희가 작업한 내용들이 Github에 올라간 상황입니다. 앞으로는 Git디렉토리에서 작업하시길 바랍니다.
![image](https://cloud.githubusercontent.com/assets/22610670/25770447/78383520-3270-11e7-8f8a-7957371db02f.png)

Git 디렉토리 경로는 다음과 같습니다.
```
/works/iothome/iothomeController
/works/iothome/jasper
```

Git 사용 방법은 아래 링크로 들어가 확인 바랍니다. 
https://rogerdudler.github.io/git-guide/index.ko.html

## 작업시 주의사항

1. 작업 하실때 **반드시 브랜치를 새로 만들어서 작업하세요.**
2. 소규모 작업 단위로 Commit 하시고 Commit 코멘트는 구체적으로 적어주세요.
3. 작업 단위가 하나 끝나면 `$ sudo git add .`를 통해 변경된 파일을 모두 추가해주시고 Push해 주세요. Push전에 꼭 `$ sudo git branch`로 현재 브렌치를 확인해주세요.
4. 작업이 모두 끝나시면  상위 브랜치 (예를 들어 develop에서 새로 추가한 브랜치라면 develop을 의미)로
 이동해서 Merge 해주십시요. Merge한 후 해당 브렌치를 Push를 해야 Github에 적용됩니다.

**Comment by pyj9293** [comment]
처음 프로젝트 통째로 올릴 때 어떻게 올리셨나요?

**Comment by MyungwoonKim** [comment]
@pyj9293 
>처음 프로젝트 통째로 올릴 때 어떻게 올리셨나요?

디렉토리를 직접 만들어서 jasper안에 있는 파일 싹 긁어 왔습니다

**Comment by pyj9293** [comment]
알겠습니다

**Comment by pyj9293** [comment]
수고하셨습니다
