### ISSUE TITLE
라즈베리파이 sudo apt-get 명령어 이용 시 ftp 연결 불가 현상 이슈

### ISSUE THREAD

**Issue by hJayLee** [pyj9293/iothome#5]
sudo apt-get install 명령어 사용 시 ftp.kaist.ac.kr 서버에 접속이 안됩니다.

0% 상태에서 계속해서 연결 시도 후에 연결 초과로 설치가 불가한 현상이 생기는데 확인 부탁드립니다.

**Comment by hJayLee** [comment]
sudo apt-get install 명령어 사용 시 ftp.kaist.ac.kr 서버에 접속이 안됩니다.

0% 상태에서 계속해서 연결 시도 후에 연결 초과로 설치가 불가한 현상이 생기는데 확인 부탁드립니다.

**Comment by pyj9293** [comment]
> sudo apt-get install 명령어 사용 시 ftp.kaist.ac.kr 서버에 접속이 안됩니다.
0% 상태에서 계속해서 연결 시도 후에 연결 초과로 설치가 불가한 현상이 생기는데 확인 부탁드립니다.

@hJayLee 알겠습니다 서버가 될 때까지 보류하겠습니다
