### ISSUE TITLE
Open Weather Map Api를 이용한 날씨 정보를 라즈베리파이에 출력

### ISSUE THREAD

**Issue by pyj9293** [pyj9293/iothome#7]
날씨 정보를 파이썬으로 가져오기

**Comment by pyj9293** [comment]
`import urllib
import json
import datetime

loca = ""
url = 'http://api.openweathermap.org/data/2.5/weather?q=Tonghae,KR&APPID=2744d18701bee380deab073a169e2136'
u = urllib.urlopen(url)
data = u.read()
print data
 
j = json.loads(data)
 
 
name = j["name"]
print "City name:"
print name
print "\n"
 
dt = j["dt"]
print "Data receiving time:"
print datetime.datetime.fromtimestamp(int(dt)).strftime('%Y-%m-%d %H:%M:%S')
print "\n"
 
main = j["main"]
temp = main["temp"]
print "temperature:"
print int(temp)-273.15
print "\n"

main = j["main"]
humidity = main["humidity"]
print "humidity:"
print "%"
print "\n"

weather = j["weather"]
main = weather[0]
print main["main"]
print main["description"]`

**Comment by pyj9293** [comment]
```
#-*- coding: euc-kr -*-
import urllib
import json
import datetime

loca = ""
url = 'http://api.openweathermap.org/data/2.5/weather?q=Tonghae,KR&APPID=2744d18701bee380deab073a169e2136'
u = urllib.urlopen(url)
data = u.read()
print data
 
j = json.loads(data)
 
 
name = j["name"]
print "City name:"
print name
print "\n"
 
dt = j["dt"]
print "Data receiving time:"
print datetime.datetime.fromtimestamp(int(dt)).strftime('%Y-%m-%d %H:%M:%S')
print "\n"
 
main = j["main"]
temp = main["temp"]
print "기온:"
print int(temp)-273.15
print "\n"

main = j["main"]
humidity = main["humidity"]
print "습도:"
print int(humidity)
print "\n"

weather = j["weather"]
main = weather[0]
print main["main"]
print main["description"]
```

**Comment by pyj9293** [comment]
출력

> {"coord":{"lon":129.11,"lat":37.54},"weather":[{"id":741,"main":"Fog","description":"fog","icon":"50n"}],"base":"stations","main":{"temp":273.73,"pressure":1027,"humidity":86,"temp_min":271.15,"temp_max":276.15},"wind":{"speed":1.5,"deg":80},"clouds":{"all":1},"dt":1483624800,"sys":{"type":1,"id":8512,"message":0.1724,"country":"KR","sunrise":1483569522,"sunset":1483604388},"id":1892823,"name":"Tonghae","cod":200}
> City name:
> Tonghae
> 
> 
> Data receiving time:
> 2017-01-05 23:00:00
> 
> 
> 기온:
> -0.15
> 
> 
> 습도:
> 86
> 
> 
> Fog
> fog

**Comment by pyj9293** [comment]
`{"coord":{"lon":129.11,"lat":37.54},"weather":[{"id":741,"main":"Fog","description":"fog","icon":"50n"}],"base":"stations","main":{"temp":273.73,"pressure":1027,"humidity":86,"temp_min":271.15,"temp_max":276.15},"wind":{"speed":1.5,"deg":80},"clouds":{"all":1},"dt":1483624800,"sys":{"type":1,"id":8512,"message":0.1724,"country":"KR","sunrise":1483569522,"sunset":1483604388},"id":1892823,"name":"Tonghae","cod":200}
City name:
Tonghae


Data receiving time:
2017-01-05 23:00:00


기온:
-0.15


습도:
86


Fog
fog`

**Comment by pyj9293** [comment]
검토바랍니다

**Comment by MyungwoonKim** [comment]
검토 완료 했습니다.
파싱 방법이 간단하군요. 수고하셨습니다.
