### ISSUE TITLE
파이썬에서 웹 사이트로 정보를 넘겨주는 방법

### ISSUE THREAD

**Issue by MyungwoonKim** [pyj9293/iothome#8]
@MyungwoonKim

요구 ID : none
파이썬에서 웹 사이트로 정보를 넘겨주는 방법 확인
웹사이트의 정보를 받는 주 언어는 JSP로 가정한다.

**Comment by MyungwoonKim** [comment]
>요구 ID : none
>파이썬에서 웹 사이트로 정보를 넘겨주는 방법 확인
>웹사이트의 정보를 받는 주 언어는 JSP로 가정한다.

* 파이썬에서 웹으로 데이터를 전달하는 방법.
1. DB를 이용한 방법. http://miscel.tistory.com/6
2. JSP를 사용할 경우 GET과 POST 방식으로 파라미터를 전달하는 방법. http://pjongy.tistory.com/96
: 1, 2번 둘다 사용할 확률이 높으며 두 기능 다 개발 경험이 있음.

* 웹사이트에서 파이썬으로 데이터를 전달하는 방법
1. JSON형태로 뿌려진 String을 파씽하는 방법. http://webnautes.tistory.com/697
2. BeautifulSoup를 이용해 해당 클래스의 태그를 긁어오는 방법. http://ourcstory.tistory.com/77
: 1번의 경우 특수의 정보를 (ex : 날씨) 불러오는데 많이 사용, 잡다한 데이터의 경우는 2번이 효율적으로 보임. 단 특정 태그를 해독할 수 있는 알고리즘 필요. 
예를 들어 <a href=# class='test'>테스트</a> 태그에서  "테스트"라는 문자열을 읽고자 할때 읽을 수 있는 메커니즘이 필요.

**Comment by pyj9293** [comment]
@MyungwoonKim 

> 파이썬에서 웹으로 데이터를 전달하는 방법.
DB를 이용한 방법. http://miscel.tistory.com/6
JSP를 사용할 경우 GET과 POST 방식으로 파라미터를 전달하는 방법. http://pjongy.tistory.com/96
: 1, 2번 둘다 사용할 확률이 높으며 두 기능 다 개발 경험이 있음.
웹사이트에서 파이썬으로 데이터를 전달하는 방법
JSON형태로 뿌려진 String을 파씽하는 방법. http://webnautes.tistory.com/697
BeautifulSoup를 이용해 해당 클래스의 태그를 긁어오는 방법. http://ourcstory.tistory.com/77
: 1번의 경우 특수의 정보를 (ex : 날씨) 불러오는데 많이 사용, 잡다한 데이터의 경우는 2번이 효율적으로 보임. 단 특정 태그를 해독할 수 있는 알고리즘 필요.
예를 들어 테스트 태그에서 "테스트"라는 문자열을 읽고자 할때 읽을 수 있는 메커니즘이 필요.

검토했습니다.
